### PR TITLE
fix err() argument to indicate error function name

### PR DESCRIPTION
**Pull request by kinichiro**
fix err() argument to indicate error function name

### CODE REVIEW

**Comment by kinichiro** [comment]
oh, really :-)
but with gcc 4.7.1 on hp-ux 11i(11.31), I'm getting this compilation warning and error.

```
ntpd.c:639:3: error: expected ')' before string constant
ntpd.c:639:3: warning: null argument where non-null required (argument 2) [-Wnonnull]
```

replacing 2nd argument NULL with some string like "malloc:"  avoids this issue.

**Comment by busterb** [comment]
Thanks for the context. The root cause is really my lame err.h backwards-compatibility macros. I'll fix those up too.

**Comment by busterb** [comment]
I fixed the macro to work properly and added the argument anyway (along with a few others). Let me know if you run into any issues with it, I only tested the updated macro on Linux.

**Comment by kinichiro** [comment]
Thanks.
It worked well with gcc 4.7.1 on hp-ux 11i(11.31), too.
